name: ci
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'
      - name: Build
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: wintund-macos
          path: build/wintund.tar.gz
